//! Vulkan media pipeline: dmabuf import, the AVC444 split and recombine as
//! compute shaders, and H.264 encode/decode through Vulkan Video.
//!
//! This is the only crate in gliff with `unsafe`: Vulkan is a C API and
//! `ash` marks every call unsafe. Callers see plain Rust types.

pub mod h264;

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("vulkan: {0}")]
    Vk(#[from] ash::vk::Result),
    #[error("vulkan loader: {0}")]
    Load(#[from] ash::LoadingError),
    #[error("no suitable GPU: {0}")]
    NoDevice(&'static str),
    #[error("bitstream: {0}")]
    Bitstream(&'static str),
    #[error("unsupported: {0}")]
    Unsupported(String),
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
}

pub type Result<T> = std::result::Result<T, Error>;
pub mod compute;
pub mod device;
pub mod encoder;
pub mod image;

/// An all-zero value of a plain C struct from the Vulkan video headers. The
/// `StdVideo*` types are integer fields and bitfields, for which zero is the
/// "nothing set" state.
pub(crate) fn zeroed<T: Copy>() -> T {
    // SAFETY: only used with `repr(C)` integer/bitfield structs generated by
    // bindgen, for which the all-zero bit pattern is a valid value.
    unsafe { std::mem::zeroed() }
}
pub mod decoder;
pub mod pipeline;

pub use device::Gpu;
pub use encoder::{EncoderSettings, Reference, MAX_REFERENCES};
pub use image::{DmabufPlane, ExportedDmabuf};
pub use pipeline::{Decoder, DisplayFrame, EncodedFrame, Encoder};
