[package]
name = "gliff-client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
tokio = { workspace = true }
bytes.workspace = true
gliff-proto.workspace = true
gliff-transport.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
