// swift-tools-version:5.10
import Foundation
import PackageDescription

// The Rust session core, built by build.sh into ../target/release.
let rustLib = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
    .deletingLastPathComponent().appendingPathComponent("target/release").path

let package = Package(
    name: "Gliff",
    platforms: [.macOS(.v14)],
    products: [.executable(name: "Gliff", targets: ["Gliff"])],
    targets: [
        // gliff.h from crates/gliff-ffi (generated by build.sh), linked to
        // libgliff_ffi.a.
        .target(
            name: "CGliff",
            linkerSettings: [
                .unsafeFlags(["-L", rustLib]),
                .linkedLibrary("gliff_ffi"),
            ]
        ),
        // VideoToolbox decode and the Metal AVC444 recombine.
        .target(name: "GliffVideo"),
        // macOS key codes and layouts to what the Linux server expects.
        .target(name: "GliffInput"),
        .executableTarget(name: "Gliff", dependencies: ["CGliff", "GliffVideo", "GliffInput"]),
        .testTarget(name: "GliffVideoTests", dependencies: ["GliffVideo"]),
        .testTarget(name: "GliffInputTests", dependencies: ["GliffInput"]),
    ]
)
