[package]
name = "haver-probe"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
png.workspace = true
wayland-client.workspace = true
hypr-ipc.workspace = true
hypr-wl.workspace = true
hypr-capture.workspace = true
hypr-input.workspace = true
haver-codec.workspace = true
