[package]
name = "haver-codec"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
haver-proto.workspace = true
haver-gl.workspace = true
cros-codecs.workspace = true
gbm.workspace = true
drm-fourcc.workspace = true
rayon.workspace = true
