[package]
name = "haver-client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio = { workspace = true }
gtk4.workspace = true
libadwaita.workspace = true
haver-proto.workspace = true
haver-transport.workspace = true
haver-codec.workspace = true
haver-gl.workspace = true
drm-fourcc.workspace = true
hypr-ipc.workspace = true
hypr-input.workspace = true
