[package]
name = "gliff-probe"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
png.workspace = true
wayland-client.workspace = true
hypr-ipc.workspace = true
hypr-wl.workspace = true
hypr-capture.workspace = true
hypr-input.workspace = true
gliff-transport.workspace = true
gliff-proto.workspace = true
gliff-vk.workspace = true
gliff-sw.workspace = true
drm-fourcc.workspace = true
tokio.workspace = true
