[package]
name = "gliff-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio = { workspace = true }
bytes.workspace = true
gliff-proto.workspace = true
gliff-transport.workspace = true
gliff-vk.workspace = true
drm-fourcc.workspace = true
hypr-capture.workspace = true
hypr-input.workspace = true
hypr-ipc.workspace = true
hypr-wl.workspace = true
dbus = "0.9"
